# -*- coding: utf-8 -*-
"""python_dictionaries.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LpAF67nFflaZji7AgGPweDr_WgTWxMPZ
"""

def decimal_to_binary(n):
  if n == 0:
    return "0"
  binary = ""
  while n > 0:
    binary += str(n % 2)
    n = n // 2
  return binary

decimal_to_binary(2)

def bin_dict(numbers):
  d = {}
  for n in range(numbers):
    d[n] = decimal_to_binary(n)
  return d

bin_dict(15)

