# -*- coding: utf-8 -*-
"""data_imputation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DP-S9ZaBovx2cYcxR19XKX2KWoyjfunZ
"""

#QUIZ
 # We want to handle missing or null values as they could break calculations in the dataset and potentially skew the outcome.

import pandas as pd
import numpy as np

#1
df = pd.read_csv('/content/titanic.csv')

df

df.isna().sum()

#2
med_age = df['Age'].median()

df['Age_med']=df['Age'].fillna(med_age)

df['Age_med'].isna().sum()

#3
df['Age_mean_sex'] = df.groupby('Sex', group_keys=False)['Age'].apply(lambda x: x.fillna(x.mean()))

df['Age_mean_sex'].isna().sum()

#4
df.info()

df.isna().sum()

df['Cabin'] = df.groupby('Pclass', group_keys=False)['Cabin'].apply(lambda x: x.fillna(x.mode()[0]))

df['Cabin'].isna().sum()

#My thought process for this question was to group Cabin and Pclass together since the Pclass would dicate where the passengers are assigned to a Cabin as certain Cabin can only belong to 1 of the 3 classes. We then can fill in the missing values with Pclass with mode since the next missing Cabin value would most likely be in the same Pclass.