# -*- coding: utf-8 -*-
"""scraping_formula1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qfMevTiwmRIvQMPVCYQJB3Ph7STUKESG
"""

from bs4 import BeautifulSoup
import requests
import pandas as pd

url = "https://www.formula1.com/en/results.html/2022/drivers.html"
rq = requests.get(url)

rq.status_code

rq.content

soup = BeautifulSoup(rq.content)

tables = soup.find_all('table')

tables[0]

data_table = tables[0]

data_table

header_data = data_table.find_all('th')

headers = []
for h in header_data:
  name = h.get_text().strip()
  headers.append(name)

headers

row_data = data_table.find_all('tr')

rows = []
for tr in row_data[1:]:
  tds = tr.find_all('td')
  row = [td.get_text() for td in tds]
  rows.append(row)

rows

df = pd.DataFrame(rows, columns = headers)
df

df.to_csv('f1_drv_standings_2k22.csv', index = False)

df_new = pd.read_csv('f1_drv_standings_2k22.csv')
df_new

df_html = pd.read_html(url)[0]
df_html

