# -*- coding: utf-8 -*-
"""is_anagram.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lH4v_vZIRVXxHRLbvT-Iqdjzp8H4z7XT
"""

def is_anagram(str_1, str_2):
  if sorted(str_1) == sorted(str_2):
    return True
  else:
    return False

str_1 = 'rat'
str_2 = 'tar'
is_anagram(str_1, str_2)

