# -*- coding: utf-8 -*-
"""reading_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EkPUI7j1xyo-OR02TeBqY6i63gcIeXXQ
"""

import pandas as pd

"""mtcars.csv"""

df_mtcars = pd.read_csv('mtcars.csv')

df_mtcars

df_mtcars.to_csv('mtcars_new.csv', index=False)

df_new_mtcars = pd.read_csv('mtcars_new.csv')

df_new_mtcars

df_mtcars.equals(df_new_mtcars)

"""u.data"""

df_u_data = pd.read_csv('u.data', sep= "\t")

df_u_data

df_u_data.to_csv('u_new.data', index=False)

df_u_new_data = pd.read_csv('u_new.data')

df_u_new_data

df_u_data.equals(df_u_new_data)

"""beer.txt"""

df_beer = pd.read_csv('beer.txt', sep = " ")

df_beer

df_beer.to_csv('beer_new.txt', index=False)

df_new_beer = pd.read_csv('beer_new.txt')

df_new_beer

df_beer.equals(df_new_beer)

"""u.item"""

df_u_item = pd.read_csv('u.item', sep = "|", encoding='latin-1')

df_u_item

df_u_item.to_csv('u_new.item', index=False)

df_new_u_time = pd.read_csv('u_new.item')

df_new_u_time

df_u_item.equals(df_new_u_time)



"""NHL 2015-16.xlsx"""

df_NHL = pd.read_excel('NHL 2015-16.xlsx')

df_NHL

df_NHL.to_excel('NHL_new.xlsx', index = False)

df_new_NHL = pd.read_excel('NHL_new.xlsx')

df_new_NHL

df_NHL.equals(df_new_NHL)

"""Function to read all file types"""

import pandas as pd
def read_all_files(file_name):

  if file_name.endswith('.csv'):
    df = pd.read_csv(file_name)

  elif file_name.endswith('.xlsx'):
    df = pd.read_excel(file_name)

  elif file_name.endswith('.data'):
    df = pd.read_csv(file_name, sep= "\t")

  elif file_name.endswith('.item'):
    df = pd.read_csv(file_name, sep = "|", encoding='latin-1')

  elif file_name.endswith('.txt'):
    df = pd.read_csv(file_name, sep = " ")
  return df

read_all_files('u.item')

