# -*- coding: utf-8 -*-
"""telecom_db.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1suAuhHcP06mytfGoTlfWFLDwuAR4f71R
"""

import sqlite3
import pandas as pd

conn = sqlite3.connect('/content/telecom.db')

tables = conn.execute("SELECT name FROM sqlite_master WHERE type = 'table'")

tables.fetchall()

joined = conn.execute("""
                      SELECT t.id, location, fault_severity, event_type, severity_type, resource_type, log_feature, volume
                      FROM train t
                      JOIN event_type et
                      ON t.id = et.id
                      JOIN severity_type st
                      ON t.id = st.id
                      JOIN resource_type rt
                      ON t.id = rt.id
                      JOIN log_feature lf
                      ON t.id = lf.id
                      """).fetchall()

conn.execute("DROP TABLE IF EXISTS joint_tables")

conn.execute("CREATE TABLE joint_tables(id, location, fault_severity, event_type, severity_type, resource_type, log_feature, volume)")

conn.executemany("INSERT INTO joint_tables VALUES(?, ?, ?, ?, ?, ?, ?, ?)", joined)

conn.execute("""
              SELECT event_type, severity_type, COUNT(*)
              FROM joint_tables
              GROUP BY event_type, severity_type
            """).fetchall()

conn.execute("""
              SELECT fault_severity, COUNT(*)
              FROM joint_tables
              GROUP BY fault_severity
            """).fetchall()

