# -*- coding: utf-8 -*-
"""reading_json.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R1M1FIJovBLR3ZasjrHEc1Bfe4SkCRlc

json_file.txt
"""

import json

data = '{"id": 1, "name": "Zia Khan", "sports": ["Ice Hockey", "Cricket"]}, {"id": 2, "name": "Dennis T", "sports": ["Football", "Basketball"]}'

type(data)

data = "[" + data + "]"
json_text = json.loads(data)

json_text

for item in json_text:
  for key, value in item.items():
      print(key,":", value)
  print("=============================================================================")

"""daily covid cases"""

with open("daily_covid_cases.json", "r") as f:
  covid_cases = json.load(f)
covid_cases

for key, value in covid_cases.items():
  print(key)
  for k, v in covid_cases[key].items():
    print(f'{k}: {v}')
  print('\n')

