# -*- coding: utf-8 -*-
"""stroke_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rH9uBUT9btl3F2GWIFu2WG1Oq8g13tlU
"""

import pandas as pd

stroke_df = pd.read_csv('/content/healthcare-dataset-stroke-data.csv')
stroke_df

stroke_df.info()

stroke_df.describe(include='float64')

group_stroke = stroke_df.groupby("stroke")
group_stroke

stroke_1 = group_stroke.get_group(1)
stroke_1

stroke_1.describe()

stroke_1.describe(percentiles=[], include='int64')

hyper_disease = stroke_df.groupby(['hypertension', 'heart_disease'])
hyper_disease

hyper_disease.get_group((1,1))

hyper_disease['id'].nunique()

hyper_disease['stroke'].agg(['mean', 'std'])

