# -*- coding: utf-8 -*-
"""birthday.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_qsT3etlfX7XkZc6jXFyL_RE2sh_GrJ8
"""

import datetime as dt

def calculate_age(birthdate):
  today = dt.date.today()
  age = today.year - birthdate.year
  return age

birthdate = dt.date(1999, 10, 14)
calculate_age(birthdate)

