# -*- coding: utf-8 -*-
"""thanksgiving.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hk-68Z30HfgP65YG1wUyDOLuwrzQI6l3
"""

import datetime as dt

today = dt.date.today()

today

thanksgiving = dt.date(2024, 11, 28)

days_to_thanksgiving = thanksgiving - today

days_to_thanksgiving

