# -*- coding: utf-8 -*-
"""python_lists_and_tuples.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zFCSYyAomj29FHmHjxapqJss4_r3LF7v

Exercise 1
"""

alphabet_list = []
index_list = []
L = 'abcdefghijklmnopqrstuvwxyz'

def list_to_tuple(L):
  for i in range(len(L)):
    alphabet_list.append(L[i])
    index_list.append(i+1)
    new_list = list(zip(index_list, alphabet_list))
  print(new_list)

list_to_tuple(L)

