# -*- coding: utf-8 -*-
"""human_resources_db.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gdsxA40CPSMNblK5C1K65AHqRIjmmROM
"""

import sqlite3
import pandas as pd

conn = sqlite3.connect("/content/hr.db")
conn

tables = conn.execute("SELECT name FROM sqlite_master WHERE type = 'table'")

tables.fetchall()

employee = conn.execute("SELECT EmployeeNumber, Department, Age, Gender, Attrition FROM employee WHERE Department = 'Sales'").fetchall()

employee

employee_cols = conn.execute("PRAGMA table_info(employee)").fetchall()
employee_cols

employee_cols = ['EmployeeNumber', 'Department', 'Age', 'Gender', 'Attrition']
employee_cols

sales = pd.DataFrame(employee, columns = employee_cols)
sales

employee_f = conn.execute("SELECT EmployeeNumber, EducationField, Age, Gender, Attrition FROM employee WHERE EducationField = 'Life Sciences'").fetchall()
employee_f

employee_f_cols = conn.execute("PRAGMA table_info(employee)").fetchall()
employee_f_cols

employee_f_cols = ['EmployeeNumber', 'EducationField', 'Age', 'Gender', 'Attrition']
employee_f_cols

field = pd.DataFrame(employee_f, columns = employee_f_cols)
field

sales.to_sql('sales', conn, if_exists = 'replace', index = False)
field.to_sql('field', conn, if_exists = 'replace', index = False)

joined = conn.execute("""
                      SELECT s.EmployeeNumber, s.Department, s.Age, s.Gender, s.Attrition, f.EducationField
                      FROM sales s
                      JOIN field f
                      ON s.EmployeeNumber = f.EmployeeNumber
                      """).fetchall()
joined

