# -*- coding: utf-8 -*-
"""tmdb_api.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hhe6ahF5KLA-Bg9D9JGs6bRSP3cv5N9M
"""

import json
import requests
import pandas as pd
from bs4 import BeautifulSoup

api_key = "1be2e424e33b46f6a5036d21323d78dd"
url = "https://api.themoviedb.org/3/search/movie?query=Star+Wars&api_key=1be2e424e33b46f6a5036d21323d78dd"

data = requests.get(url)
data

data.content

data.text

data_obj = json.loads(data.text)
data_obj

len(data_obj['results'])

data.json().keys()

data.json()['total_pages']

url_pages = "https://api.themoviedb.org/3/search/movie?query=Star+Wars&api_key=1be2e424e33b46f6a5036d21323d78dd&page="
data_pages = requests.get(url_pages)
data_pages.json()

full_data = []
for page in range(1, 11):
    url_10 = (url_pages + str(page))
    data_ten_pages = requests.get(url_10)
    full_data += data_ten_pages.json()['results']

full_data

len(full_data)

df = pd.DataFrame(full_data)
df

df.sort_values(by='popularity', ascending = False)

