# -*- coding: utf-8 -*-
"""pandas_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WVgcNrhDhajfFqhxVLrj1JD7OAbUDg9Y
"""

#part 1
import numpy as np
import pandas as pd

#part 2
loans = pd.read_csv('/content/Loan payments data.csv')
loans

#part 3
loans.head(7)

#part 4
loans.tail(3)

#part 5
random_loans = loans.sample(frac=0.25)
random_loans.head(5)

#part 6
loans.sample(10)

#part 7
loans.value_counts(['loan_status'])

loans.value_counts(['City'])

#part 8
loans.iloc[200]

#part 9
loans[['education']]

#part 10
loans[['loan_status']]

#part 11
loans.iloc[:,8]

#part 12
loans.iloc[2:7]

#part 13
loans.iloc[:,-3:]

#part 14
loans[loans.Gender=='female']

#part 15
loans[(loans.City=='NYC') & (loans.education=='college')]

#part 16
loans[loans.age>32]

#part 17
loans.loc[(loans.past_due_days > 7), ['due_date', 'past_due_days']]

