# -*- coding: utf-8 -*-
"""bracket_matcher.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yw18vXfys9ZCCcipHqjlGD1O65-SUAI3
"""

def Bracket_Matcher(string):
  count = 0
  for char in string:
    if char == '(':
      count += 1
    elif char == ')':
      count -= 1
  if count == 0:
    return True
  else:
    return False

s = '(a((kl(mns)t)uvwz)'
Bracket_Matcher(s)

