# -*- coding: utf-8 -*-
"""merge_join_telecom.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UByIiHRAQMWkXxeAXuM3lhnEV46Dzceh
"""

import pandas as pd

event_df = pd.read_csv('/content/event_type.csv')
log_df = pd.read_csv('/content/log_feature.csv')
res_df = pd.read_csv('/content/resource_type.csv')
sevr_df = pd.read_csv('/content/severity_type.csv')
train_df = pd.read_csv('/content/train.csv')

df_merged_1 = pd.merge(event_df, log_df)
df_merged_2 = pd.merge(df_merged_1, res_df)
df_merged_3 = pd.merge(df_merged_2, sevr_df)
df_merged_4 = pd.merge(df_merged_3, train_df)

#inner merge use intersection of keys from both dataframes
#outer merge use union of keys from both dataframes
#merge combine DataFrames based on specific columns
#join combine DataFrames bases on the indices between the two

df_merged_4

df1 = df_merged_4[:31000]
df2 = df_merged_4[31000:]

df_new = pd.concat([df1, df2])

df_merged_4.equals(df_new)

df_merged_4.duplicated().sum()